from __future__ import annotations

from PySide6.QtCore import QLocale


SUPPORTED_LOCALES = ("uk", "en", "pl")


def system_locale() -> str:
    candidate = QLocale.system().name().split("_", 1)[0].lower()
    return candidate if candidate in SUPPORTED_LOCALES else "uk"


def t(locale: str, key: str, **values: str) -> str:
    return TEXT[locale].get(key, TEXT["uk"][key]).format(**values)


_uk = {
    "app_name": "Advanced Serial Vision", "open": "Відкрити", "exit": "Вийти", "recognition": "Розпізнавання", "equipment": "Обладнання", "models": "Моделі", "statistics": "Статистика", "settings": "Налаштування", "help": "Довідка", "about": "Про програму", "images": "Зображення", "ocr": "OCR-розпізнавання", "barcodes": "Штрихкоди", "ai": "AI-розпізнавання", "ocr_language": "Мова OCR", "select_image": "Оберіть фото", "ocr_empty": "Результат OCR з’явиться тут.", "barcode_empty": "Результат штрихкодів з’явиться тут.", "ai_empty": "Додайте та оберіть AI-профіль у налаштуваннях.", "refresh": "Оновити", "rotate": "Повернути праворуч", "delete": "Видалити", "run_ocr": "Розпізнати OCR", "run_barcode": "Прочитати штрихкоди", "choose_folder": "Обрати папку", "open_folder": "Відкрити папку", "save": "Зберегти", "export": "Експорт CSV", "language": "Мова інтерфейсу", "image_folder": "Папка з фото", "ai_profiles": "AI-профілі", "profile_name": "Назва", "provider": "Постачальник", "model": "Модель", "api_key": "API-ключ", "add_profile": "Додати профіль", "remove_profile": "Видалити профіль", "no_profiles": "AI-профілі ще не налаштовані.", "developer": "Розробник: homeandriy", "version": "Версія {version}", "type": "Тип", "service": "Послуга", "all_types": "Усі типи", "all_services": "Усі послуги", "modem": "Модем", "tuner": "Тюнер", "internet": "Інтернет", "television": "Телебачення", "receipt": "Прийом", "issue": "Видача", "operation": "Операція", "contract": "Номер договору", "recognized_text": "Серійний номер / MAC / текст", "date_time": "Дата і час", "model_name": "Назва моделі", "search": "Пошук за текстом", "confirm": "Підтвердження", "error": "Помилка", "no_image": "Спершу виберіть зображення.", "folder_missing": "Вибрана папка не існує або недоступна.", "profile_saved": "AI-профіль збережено.", "profile_required": "Оберіть AI-профіль.", "restart_language": "Мову збережено. Вона застосовується після перезапуску.", "status_ready": "Готово", "barcodes_not_found": "Штрихкодів не знайдено.", "about_text": "Локальний облік обладнання та OCR.", "delete_image": "Видалити вибране фото? Запис обладнання залишиться.", "delete_device": "Видалити вибраний запис обладнання?", "delete_model": "Видалити вибрану модель?"}

_en = {"app_name": "Advanced Serial Vision", "recognition": "Recognition", "equipment": "Equipment", "models": "Models", "statistics": "Statistics", "settings": "Settings", "help": "Help", "about": "About", "images": "Images", "ocr": "OCR recognition", "barcodes": "Barcodes", "ai": "AI recognition", "ocr_language": "OCR language", "select_image": "Select an image", "ocr_empty": "OCR result will appear here.", "barcode_empty": "Barcode result will appear here.", "ai_empty": "Add and select an AI profile in Settings.", "refresh": "Refresh", "rotate": "Rotate right", "delete": "Delete", "run_ocr": "Run OCR", "run_barcode": "Read barcodes", "choose_folder": "Choose folder", "open_folder": "Open folder", "save": "Save", "export": "Export CSV", "language": "Interface language", "image_folder": "Image folder", "ai_profiles": "AI profiles", "profile_name": "Name", "provider": "Provider", "model": "Model", "api_key": "API key", "add_profile": "Add profile", "remove_profile": "Remove profile", "no_profiles": "No AI profiles configured.", "developer": "Developer: homeandriy", "version": "Version {version}", "type": "Type", "service": "Service", "all_types": "All types", "all_services": "All services", "modem": "Modem", "tuner": "Tuner", "internet": "Internet", "television": "Television", "receipt": "Receipt", "issue": "Issue", "operation": "Operation", "contract": "Contract number", "recognized_text": "Serial number / MAC / text", "date_time": "Date and time", "model_name": "Model name", "search": "Search text", "confirm": "Confirmation", "error": "Error", "no_image": "Select an image first.", "folder_missing": "The selected folder is unavailable.", "profile_saved": "AI profile saved.", "profile_required": "Select an AI profile.", "restart_language": "Language saved. It will apply after restart.", "status_ready": "Ready", "barcodes_not_found": "No barcodes found.", "about_text": "Local equipment records and OCR.", "delete_image": "Delete selected photo? Equipment records stay.", "delete_device": "Delete selected equipment record?", "delete_model": "Delete selected model?"}

_pl = {"app_name": "Advanced Serial Vision", "recognition": "Rozpoznawanie", "equipment": "Sprzęt", "models": "Modele", "statistics": "Statystyki", "settings": "Ustawienia", "help": "Pomoc", "about": "O programie", "images": "Obrazy", "ocr": "Rozpoznawanie OCR", "barcodes": "Kody kreskowe", "ai": "Rozpoznawanie AI", "ocr_language": "Język OCR", "select_image": "Wybierz obraz", "ocr_empty": "Wynik OCR pojawi się tutaj.", "barcode_empty": "Wynik kodów pojawi się tutaj.", "ai_empty": "Dodaj i wybierz profil AI w Ustawieniach.", "refresh": "Odśwież", "rotate": "Obróć w prawo", "delete": "Usuń", "run_ocr": "Uruchom OCR", "run_barcode": "Odczytaj kody", "choose_folder": "Wybierz folder", "open_folder": "Otwórz folder", "save": "Zapisz", "export": "Eksport CSV", "language": "Język interfejsu", "image_folder": "Folder obrazów", "ai_profiles": "Profile AI", "profile_name": "Nazwa", "provider": "Dostawca", "model": "Model", "api_key": "Klucz API", "add_profile": "Dodaj profil", "remove_profile": "Usuń profil", "no_profiles": "Brak profili AI.", "developer": "Programista: homeandriy", "version": "Wersja {version}", "type": "Typ", "service": "Usługa", "all_types": "Wszystkie typy", "all_services": "Wszystkie usługi", "modem": "Modem", "tuner": "Tuner", "internet": "Internet", "television": "Telewizja", "receipt": "Przyjęcie", "issue": "Wydanie", "operation": "Operacja", "contract": "Numer umowy", "recognized_text": "Numer seryjny / MAC / tekst", "date_time": "Data i czas", "model_name": "Nazwa modelu", "search": "Szukaj tekstu", "confirm": "Potwierdzenie", "error": "Błąd", "no_image": "Najpierw wybierz obraz.", "folder_missing": "Wybrany folder jest niedostępny.", "profile_saved": "Profil AI zapisano.", "profile_required": "Wybierz profil AI.", "restart_language": "Język zapisano. Zostanie zastosowany po restarcie.", "status_ready": "Gotowe", "barcodes_not_found": "Nie znaleziono kodów kreskowych.", "about_text": "Lokalna ewidencja sprzętu i OCR.", "delete_image": "Usunąć wybrane zdjęcie? Rekordy sprzętu pozostaną.", "delete_device": "Usunąć wybrany rekord sprzętu?", "delete_model": "Usunąć wybrany model?"}

TEXT = {"uk": _uk, "en": _en, "pl": _pl}
for _locale, _values in TEXT.items():
    _values.setdefault("open", {"en": "Open", "pl": "Otwórz"}.get(_locale, "Відкрити"))
    _values.setdefault("exit", {"en": "Exit", "pl": "Wyjdź"}.get(_locale, "Вийти"))
    _values.setdefault("copy", {"en": "Copy", "pl": "Kopiuj"}.get(_locale, "Копіювати"))
    _values.setdefault("add_to_database", {"en": "Add to database", "pl": "Dodaj do bazy"}.get(_locale, "Додати в БД"))
    _values.setdefault("add_raw_to_database", {"en": "Add unformatted to database", "pl": "Dodaj bez formatowania do bazy"}.get(_locale, "Додати в БД неформатовано"))
    _values.setdefault("new_equipment", {"en": "New equipment record", "pl": "Nowy wpis sprzętu"}.get(_locale, "Новий запис обладнання"))
    _values.setdefault("add_record", {"en": "Add record", "pl": "Dodaj wpis"}.get(_locale, "Додати запис"))
    _values.setdefault("edit", {"en": "Edit", "pl": "Edytuj"}.get(_locale, "Редагувати"))

_uk.update({"first_run": "Перший запуск", "license_text": "Підтвердіть згоду з умовами та оберіть папку з фото.", "accept_and_continue": "Прийняти та продовжити", "startup_log": "Відкрити лог запуску", "check_updates": "Перевірити оновлення", "update_not_configured": "Перевірка оновлень ще не налаштована."})

_en.update({"first_run": "First launch", "license_text": "Accept the terms and select the image folder.", "accept_and_continue": "Accept and continue", "startup_log": "Open startup log", "check_updates": "Check for updates", "update_not_configured": "Update checking is not configured yet."})
_pl.update({"first_run": "Pierwsze uruchomienie", "license_text": "Zaakceptuj warunki i wybierz folder obrazów.", "accept_and_continue": "Akceptuj i kontynuuj", "startup_log": "Otwórz dziennik uruchamiania", "check_updates": "Sprawdź aktualizacje", "update_not_configured": "Sprawdzanie aktualizacji nie jest jeszcze skonfigurowane."})

TEXT["uk"]["day"] = "По днях"

TEXT["en"]["day"] = "By day"
TEXT["pl"]["day"] = "Wedlug dni"
TEXT["uk"]["month"] = "По місяцях"
TEXT["en"]["month"] = "By month"
TEXT["pl"]["month"] = "Wedlug miesiecy"

TEXT["uk"]["github_repository"] = "GitHub-репозиторій оновлень"
TEXT["en"]["github_repository"] = "GitHub updates repository"
TEXT["pl"]["github_repository"] = "Repozytorium aktualizacji GitHub"
TEXT["uk"]["update_not_found"] = "Новішої версії не знайдено."
TEXT["en"]["update_not_found"] = "No newer version was found."
TEXT["pl"]["update_not_found"] = "Nie znaleziono nowszej wersji."

TEXT["uk"].update({"license_acceptance": "Я приймаю умови використання", "license_required": "Потрібно підтвердити згоду з умовами.", "source_image_missing": "Файл вихідного фото вже не існує або недоступний.", "total": "Разом"})

TEXT["en"].update({"license_acceptance": "I accept the terms of use", "license_required": "You must accept the terms.", "source_image_missing": "The linked photo no longer exists or is unavailable.", "total": "Total"})
TEXT["pl"].update({"license_acceptance": "Akceptuje warunki uzytkowania", "license_required": "Musisz zaakceptowac warunki.", "source_image_missing": "Plik zrodlowego zdjecia juz nie istnieje lub jest niedostepny.", "total": "Razem"})

TEXT["uk"].update({"contract_too_long": "Номер договору має містити до 20 символів.", "model_exists": "Модель з такою назвою, типом і послугою вже існує.", "model_in_use": "Не можна видалити модель, що використана у записах обладнання."})

TEXT["en"].update({"contract_too_long": "Contract number must not exceed 20 characters.", "model_exists": "A model with this name, type and service already exists.", "model_in_use": "A model linked to equipment records cannot be deleted."})
TEXT["pl"].update({"contract_too_long": "Numer umowy moze miec najwyzej 20 znakow.", "model_exists": "Model o tej nazwie, typie i usludze juz istnieje.", "model_in_use": "Nie mozna usunac modelu powiazanego z wpisami sprzetu."})

TEXT["uk"].update({"previous_page": "Попередня сторінка", "next_page": "Наступна сторінка"})
TEXT["en"].update({"previous_page": "Previous page", "next_page": "Next page"})
TEXT["pl"].update({"previous_page": "Poprzednia strona", "next_page": "Nastepna strona"})

TEXT["uk"]["open_source_image"] = "Відкрити вихідне фото"
TEXT["en"]["open_source_image"] = "Open source image"
TEXT["pl"]["open_source_image"] = "Otworz zdjecie zrodlowe"

TEXT["uk"].update({"menu_file": "Файл", "menu_edit": "Редагувати", "menu_view": "Вигляд", "help_contents": "Довідка", "help_text": "Оберіть фото, щоб автоматично запустити OCR і читання штрихкодів. Виділений результат можна скопіювати або додати до обліку через праву кнопку миші.", "select_text_to_copy": "Виділіть текст у полі результату, щоб скопіювати його.", "recognizing": "Виконується розпізнавання…", "interface_settings": "Інтерфейс", "folder_settings": "Папка зображень", "update_settings": "Оновлення", "save_interface": "Зберегти інтерфейс", "save_folder": "Зберегти папку", "save_updates": "Зберегти оновлення", "settings_saved": "Налаштування збережено."})
TEXT["en"].update({"menu_file": "File", "menu_edit": "Edit", "menu_view": "View", "help_contents": "Help", "help_text": "Select a photo to start OCR and barcode reading automatically. Right-click selected results to copy them or add them to equipment.", "select_text_to_copy": "Select text in a result field to copy it.", "recognizing": "Recognition in progress…", "interface_settings": "Interface", "folder_settings": "Image folder", "update_settings": "Updates", "save_interface": "Save interface", "save_folder": "Save folder", "save_updates": "Save updates", "settings_saved": "Settings saved."})
TEXT["pl"].update({"menu_file": "Plik", "menu_edit": "Edycja", "menu_view": "Widok", "help_contents": "Pomoc", "help_text": "Wybierz zdjęcie, aby automatycznie uruchomić OCR i odczyt kodów. Kliknij prawym przyciskiem zaznaczony wynik, aby go skopiować lub dodać do sprzętu.", "select_text_to_copy": "Zaznacz tekst w polu wyniku, aby go skopiować.", "recognizing": "Trwa rozpoznawanie…", "interface_settings": "Interfejs", "folder_settings": "Folder obrazów", "update_settings": "Aktualizacje", "save_interface": "Zapisz interfejs", "save_folder": "Zapisz folder", "save_updates": "Zapisz aktualizacje", "settings_saved": "Ustawienia zapisano."})

TEXT["uk"]["open_image"] = "Відкрити зображення"
TEXT["en"]["open_image"] = "Open image"
TEXT["pl"]["open_image"] = "Otwórz obraz"

TEXT["uk"].update({"automatic_update_unsupported": "Автоматичне оновлення доступне у встановленій версії SerialVision.exe. Зараз запущено dev-версію Python.", "update_integrity_failed": "Не вдалося перевірити цілісність завантаженого оновлення.", "update_available_manual": "Доступна версія {version}. Встановіть її з опублікованих файлів релізу."})
TEXT["en"].update({"automatic_update_unsupported": "Automatic updates are available in the installed SerialVision.exe. The Python development version is running now.", "update_integrity_failed": "The downloaded update could not be verified.", "update_available_manual": "Version {version} is available. Install it from the release assets."})
TEXT["pl"].update({"automatic_update_unsupported": "Automatyczne aktualizacje są dostępne w zainstalowanym SerialVision.exe. Teraz działa wersja programistyczna Python.", "update_integrity_failed": "Nie można zweryfikować pobranej aktualizacji.", "update_available_manual": "Dostępna jest wersja {version}. Zainstaluj ją z plików wydania."})

TEXT["uk"].update({"run_ai": "Розпізнати AI", "ai_recognizing": "AI-розпізнавання виконується…", "edit_profile": "Редагувати профіль", "delete_profile": "Видалити вибраний AI-профіль?", "api_key_optional": "Залиште порожнім, щоб не змінювати ключ", "profile_key_required": "Заповніть назву, модель і API-ключ.", "ai_profile_missing": "AI-профіль не знайдено."})
TEXT["en"].update({"run_ai": "Run AI recognition", "ai_recognizing": "AI recognition in progress…", "edit_profile": "Edit profile", "delete_profile": "Delete the selected AI profile?", "api_key_optional": "Leave empty to keep the current key", "profile_key_required": "Enter a name, model and API key.", "ai_profile_missing": "AI profile was not found."})
TEXT["pl"].update({"run_ai": "Rozpoznaj AI", "ai_recognizing": "Trwa rozpoznawanie AI…", "edit_profile": "Edytuj profil", "delete_profile": "Usunąć wybrany profil AI?", "api_key_optional": "Pozostaw puste, aby zachować bieżący klucz", "profile_key_required": "Podaj nazwę, model i klucz API.", "ai_profile_missing": "Nie znaleziono profilu AI."})

TEXT["uk"].update({"appearance_settings": "Оформлення", "theme": "Тема", "theme_system": "Системна (за замовчуванням)", "theme_light": "Світла", "theme_dark": "Темна", "show_button_icons": "Показувати системні значки на кнопках", "save_appearance": "Зберегти оформлення"})
TEXT["en"].update({"appearance_settings": "Appearance", "theme": "Theme", "theme_system": "System default", "theme_light": "Light", "theme_dark": "Dark", "show_button_icons": "Show system icons on buttons", "save_appearance": "Save appearance"})
TEXT["pl"].update({"appearance_settings": "Wygląd", "theme": "Motyw", "theme_system": "Systemowy (domyślny)", "theme_light": "Jasny", "theme_dark": "Ciemny", "show_button_icons": "Pokazuj ikony systemowe na przyciskach", "save_appearance": "Zapisz wygląd"})

TEXT["uk"].update({"icon_style": "Стиль значків", "icon_style_system": "Стандартні системні", "icon_style_modern": "Модерн", "icon_style_classic": "Класика", "icon_style_windows98": "Windows 98", "icon_style_ubuntu22": "Ubuntu 22", "add_model": "Додати модель", "edit_model": "Редагувати модель", "usage_count": "Кількість використань", "actions": "Дії"})
TEXT["en"].update({"icon_style": "Icon style", "icon_style_system": "Standard system", "icon_style_modern": "Modern", "icon_style_classic": "Classic", "icon_style_windows98": "Windows 98", "icon_style_ubuntu22": "Ubuntu 22", "add_model": "Add model", "edit_model": "Edit model", "usage_count": "Usage count", "actions": "Actions"})
TEXT["pl"].update({"icon_style": "Styl ikon", "icon_style_system": "Standardowy systemowy", "icon_style_modern": "Nowoczesny", "icon_style_classic": "Klasyczny", "icon_style_windows98": "Windows 98", "icon_style_ubuntu22": "Ubuntu 22", "add_model": "Dodaj model", "edit_model": "Edytuj model", "usage_count": "Liczba użyć", "actions": "Działania"})

TEXT["uk"].update({"about_description": "Локальний застосунок для обліку обладнання та розпізнавання серійних номерів.", "developer_label": "Розробник", "website": "Сайт", "open_website": "Відкрити сайт", "close": "Закрити"})
TEXT["en"].update({"about_description": "Local application for equipment tracking and serial-number recognition.", "developer_label": "Developer", "website": "Website", "open_website": "Open website", "close": "Close"})
TEXT["pl"].update({"about_description": "Lokalna aplikacja do ewidencji sprzętu i rozpoznawania numerów seryjnych.", "developer_label": "Twórca", "website": "Strona internetowa", "open_website": "Otwórz stronę", "close": "Zamknij"})

TEXT["uk"]["open_file_failed"] = "Не вдалося відкрити файл: {error}"
TEXT["en"]["open_file_failed"] = "Could not open the file: {error}"
TEXT["pl"]["open_file_failed"] = "Nie można otworzyć pliku: {error}"

TEXT["uk"]["startup_log_unavailable"] = "Не вдалося записати лог запуску у папку: {path}\nПричина ОС: {error}"
TEXT["en"]["startup_log_unavailable"] = "Could not write the startup log to: {path}\nOS reason: {error}"
TEXT["pl"]["startup_log_unavailable"] = "Nie można zapisać dziennika uruchomienia w folderze: {path}\nPrzyczyna systemowa: {error}"

TEXT["uk"]["open_help_section"] = "Відкрити довідку: {section}"
TEXT["en"]["open_help_section"] = "Open help: {section}"
TEXT["pl"]["open_help_section"] = "Otwórz pomoc: {section}"

TEXT["uk"].update({"api_integrations": "API-інтеграції", "api_enabled": "Увімкнути локальний API (127.0.0.1)", "api_port": "Порт API", "api_rate": "Ліміт запитів на ключ", "api_rate_5": "5 запитів за секунду", "api_rate_2": "2 запити за секунду", "api_rate_1": "1 запит за секунду", "api_rate_half": "1 запит за 2 секунди", "save_api": "Зберегти API", "api_keys": "Bearer-ключі", "note": "Примітка", "api_key_prefix": "Префікс", "expires_at": "Діє до", "api_status": "Статус", "api_active": "Активний", "api_revoked": "Відкликаний", "issue_api_key": "Випустити ключ", "revoke_api_key": "Відкликати ключ", "revoke_api_key_confirm": "Відкликати вибраний API-ключ?", "api_key_expiry": "Обмежити строк дії", "api_key_created": "API-ключ створено", "api_key_once": "Скопіюйте ключ зараз. Пізніше його переглянути неможливо.", "api_key_name_required": "Вкажіть назву API-ключа.", "api_port_invalid": "Порт має бути від 1024 до 65535.", "api_rate_invalid": "Непідтримуваний ліміт запитів.", "api_start_failed": "Не вдалося запустити локальний API: {error}", "api_audit": "Журнал API-операцій", "method": "Метод", "path": "Шлях", "status": "Статус", "never": "Безстроково"})

TEXT["en"].update({"api_integrations": "API integrations", "api_enabled": "Enable local API (127.0.0.1)", "api_port": "API port", "api_rate": "Request limit per key", "api_rate_5": "5 requests per second", "api_rate_2": "2 requests per second", "api_rate_1": "1 request per second", "api_rate_half": "1 request per 2 seconds", "save_api": "Save API", "api_keys": "Bearer keys", "note": "Note", "api_key_prefix": "Prefix", "expires_at": "Expires at", "api_status": "Status", "api_active": "Active", "api_revoked": "Revoked", "issue_api_key": "Issue key", "revoke_api_key": "Revoke key", "revoke_api_key_confirm": "Revoke selected API key?", "api_key_expiry": "Limit validity period", "api_key_created": "API key created", "api_key_once": "Copy this key now. It cannot be viewed later.", "api_key_name_required": "Enter an API key name.", "api_port_invalid": "Port must be between 1024 and 65535.", "api_rate_invalid": "Unsupported request limit.", "api_start_failed": "Could not start local API: {error}", "api_audit": "API operation log", "method": "Method", "path": "Path", "status": "Status", "never": "Never"})
TEXT["pl"].update({"api_integrations": "Integracje API", "api_enabled": "Włącz lokalne API (127.0.0.1)", "api_port": "Port API", "api_rate": "Limit żądań na klucz", "api_rate_5": "5 żądań na sekundę", "api_rate_2": "2 żądania na sekundę", "api_rate_1": "1 żądanie na sekundę", "api_rate_half": "1 żądanie na 2 sekundy", "save_api": "Zapisz API", "api_keys": "Klucze Bearer", "note": "Notatka", "api_key_prefix": "Prefiks", "expires_at": "Wygasa", "api_status": "Status", "api_active": "Aktywny", "api_revoked": "Cofnięty", "issue_api_key": "Wydaj klucz", "revoke_api_key": "Cofnij klucz", "revoke_api_key_confirm": "Cofnąć wybrany klucz API?", "api_key_expiry": "Ogranicz okres ważności", "api_key_created": "Utworzono klucz API", "api_key_once": "Skopiuj klucz teraz. Później nie można go wyświetlić.", "api_key_name_required": "Podaj nazwę klucza API.", "api_port_invalid": "Port musi być od 1024 do 65535.", "api_rate_invalid": "Nieobsługiwany limit żądań.", "api_start_failed": "Nie można uruchomić lokalnego API: {error}", "api_audit": "Dziennik operacji API", "method": "Metoda", "path": "Ścieżka", "status": "Status", "never": "Bezterminowo"})

TEXT["uk"]["version_label"] = "Версія"
TEXT["en"]["version_label"] = "Version"
TEXT["pl"]["version_label"] = "Wersja"

TEXT["uk"].update({"import_models": "Імпорт моделей з Excel", "model_import_summary": "Додано: {added}. Пропущено дублікатів: {duplicates}. Некоректних рядків: {invalid}.", "model_import_file_type": "Оберіть файл Excel у форматі .xlsx.", "model_import_file_invalid": "Не вдалося прочитати файл Excel.", "model_import_headers": "Excel має містити колонки name, device_type, service."})
TEXT["en"].update({"import_models": "Import models from Excel", "model_import_summary": "Added: {added}. Duplicate rows skipped: {duplicates}. Invalid rows: {invalid}.", "model_import_file_type": "Choose an Excel .xlsx file.", "model_import_file_invalid": "The Excel file could not be read.", "model_import_headers": "Excel must contain name, device_type and service columns."})
TEXT["pl"].update({"import_models": "Importuj modele z Excel", "model_import_summary": "Dodano: {added}. Pominięto duplikaty: {duplicates}. Niepoprawne wiersze: {invalid}.", "model_import_file_type": "Wybierz plik Excel .xlsx.", "model_import_file_invalid": "Nie można odczytać pliku Excel.", "model_import_headers": "Excel musi zawierać kolumny name, device_type i service."})

TEXT["uk"].update({"generate_qr": "Отримати QR-код", "generate_barcode": "Отримати штрихкод", "code_preview": "Перегляд коду", "qrcode_title": "QR-код: {code}", "barcode_title": "Штрихкод Code 128: {code}", "save_png": "Зберегти PNG", "code_value_empty": "Введіть серійний номер, MAC-адресу або текст для створення коду.", "code_type_invalid": "Непідтримуваний тип коду.", "code_save_failed": "Не вдалося зберегти PNG: {error}"})
TEXT["en"].update({"generate_qr": "Get QR code", "generate_barcode": "Get barcode", "code_preview": "Code preview", "qrcode_title": "QR code: {code}", "barcode_title": "Code 128 barcode: {code}", "save_png": "Save PNG", "code_value_empty": "Enter a serial number, MAC address, or text to create a code.", "code_type_invalid": "Unsupported code type.", "code_save_failed": "Could not save PNG: {error}"})
TEXT["pl"].update({"generate_qr": "Uzyskaj kod QR", "generate_barcode": "Uzyskaj kod kreskowy", "code_preview": "Podgląd kodu", "qrcode_title": "Kod QR: {code}", "barcode_title": "Kod kreskowy Code 128: {code}", "save_png": "Zapisz PNG", "code_value_empty": "Wprowadź numer seryjny, adres MAC lub tekst, aby utworzyć kod.", "code_type_invalid": "Nieobsługiwany typ kodu.", "code_save_failed": "Nie można zapisać PNG: {error}"})

TEXT["uk"].update({"scan": "Відсканувати", "camera": "Камера", "camera_refresh": "Оновити камери", "camera_start": "Запустити камеру", "camera_stop": "Зупинити камеру", "camera_capture": "Зробити кадр", "camera_select": "Оберіть камеру та запустіть її.", "camera_unavailable": "Камера не знайдена або недоступна.", "camera_ready": "Камеру запущено. Зробіть кадр для локального розпізнавання.", "camera_stopped": "Камеру зупинено.", "camera_capturing": "Захоплення кадру…", "camera_result": "Результат сканування", "camera_result_empty": "QR або штрихкод не знайдено.", "camera_error": "Помилка камери: {error}", "copy_record": "Копіювати запис", "api_request_examples": "Побачити API-запит"})
TEXT["en"].update({"scan": "Scan", "camera": "Camera", "camera_refresh": "Refresh cameras", "camera_start": "Start camera", "camera_stop": "Stop camera", "camera_capture": "Capture frame", "camera_select": "Select a camera and start it.", "camera_unavailable": "No camera is available.", "camera_ready": "Camera is running. Capture a frame for local recognition.", "camera_stopped": "Camera stopped.", "camera_capturing": "Capturing frame…", "camera_result": "Scan result", "camera_result_empty": "No QR code or barcode was found.", "camera_error": "Camera error: {error}", "copy_record": "Copy record", "api_request_examples": "View API request"})
TEXT["pl"].update({"scan": "Skanuj", "camera": "Kamera", "camera_refresh": "Odśwież kamery", "camera_start": "Uruchom kamerę", "camera_stop": "Zatrzymaj kamerę", "camera_capture": "Zrób zdjęcie", "camera_select": "Wybierz kamerę i uruchom ją.", "camera_unavailable": "Kamera nie jest dostępna.", "camera_ready": "Kamera działa. Zrób zdjęcie do lokalnego rozpoznania.", "camera_stopped": "Kamera została zatrzymana.", "camera_capturing": "Robienie zdjęcia…", "camera_result": "Wynik skanowania", "camera_result_empty": "Nie znaleziono kodu QR ani kreskowego.", "camera_error": "Błąd kamery: {error}", "copy_record": "Kopiuj wpis", "api_request_examples": "Pokaż żądanie API"})