from __future__ import annotations

from PySide6.QtCore import QLocale


SUPPORTED_LOCALES = ("uk", "en", "pl")


def system_locale() -> str:
    candidate = QLocale.system().name().split("_", 1)[0].lower()
    return candidate if candidate in SUPPORTED_LOCALES else "uk"


def t(locale: str, key: str, **values: str) -> str:
    return TEXT[locale].get(key, TEXT["uk"][key]).format(**values)


_uk = {
    "app_name": "Serial Vision", "open": "Відкрити", "exit": "Вийти", "recognition": "Розпізнавання", "equipment": "Обладнання", "models": "Моделі", "statistics": "Статистика", "settings": "Налаштування", "help": "Довідка", "about": "Про програму", "images": "Зображення", "ocr": "OCR-розпізнавання", "barcodes": "Штрихкоди", "ai": "AI-розпізнавання", "ocr_language": "Мова OCR", "select_image": "Оберіть фото", "ocr_empty": "Результат OCR з’явиться тут.", "barcode_empty": "Результат штрихкодів з’явиться тут.", "ai_empty": "Додайте та оберіть AI-профіль у налаштуваннях.", "refresh": "Оновити", "rotate": "Повернути праворуч", "delete": "Видалити", "run_ocr": "Розпізнати OCR", "run_barcode": "Прочитати штрихкоди", "choose_folder": "Обрати папку", "open_folder": "Відкрити папку", "save": "Зберегти", "export": "Експорт CSV", "language": "Мова інтерфейсу", "image_folder": "Папка з фото", "tesseract": "Tesseract executable", "ai_profiles": "AI-профілі", "profile_name": "Назва", "provider": "Постачальник", "model": "Модель", "api_key": "API-ключ", "add_profile": "Додати профіль", "remove_profile": "Видалити профіль", "no_profiles": "AI-профілі ще не налаштовані.", "developer": "Розробник: homeandriy", "version": "Версія {version}", "type": "Тип", "service": "Послуга", "all_types": "Усі типи", "all_services": "Усі послуги", "modem": "Модем", "tuner": "Тюнер", "internet": "Інтернет", "television": "Телебачення", "receipt": "Прийом", "issue": "Видача", "operation": "Операція", "contract": "Номер договору", "recognized_text": "Серійний номер / MAC / текст", "date_time": "Дата і час", "model_name": "Назва моделі", "search": "Пошук за текстом", "confirm": "Підтвердження", "error": "Помилка", "no_image": "Спершу виберіть зображення.", "folder_missing": "Вибрана папка не існує або недоступна.", "profile_saved": "AI-профіль збережено.", "profile_required": "Оберіть AI-профіль.", "restart_language": "Мову збережено. Вона застосовується після перезапуску.", "status_ready": "Готово", "barcodes_not_found": "Штрихкодів не знайдено.", "about_text": "Локальний облік обладнання та OCR.", "delete_image": "Видалити вибране фото? Запис обладнання залишиться.", "delete_device": "Видалити вибраний запис обладнання?", "delete_model": "Видалити вибрану модель?"}

_en = {"app_name": "Serial Vision", "recognition": "Recognition", "equipment": "Equipment", "models": "Models", "statistics": "Statistics", "settings": "Settings", "help": "Help", "about": "About", "images": "Images", "ocr": "OCR recognition", "barcodes": "Barcodes", "ai": "AI recognition", "ocr_language": "OCR language", "select_image": "Select an image", "ocr_empty": "OCR result will appear here.", "barcode_empty": "Barcode result will appear here.", "ai_empty": "Add and select an AI profile in Settings.", "refresh": "Refresh", "rotate": "Rotate right", "delete": "Delete", "run_ocr": "Run OCR", "run_barcode": "Read barcodes", "choose_folder": "Choose folder", "open_folder": "Open folder", "save": "Save", "export": "Export CSV", "language": "Interface language", "image_folder": "Image folder", "tesseract": "Tesseract executable", "ai_profiles": "AI profiles", "profile_name": "Name", "provider": "Provider", "model": "Model", "api_key": "API key", "add_profile": "Add profile", "remove_profile": "Remove profile", "no_profiles": "No AI profiles configured.", "developer": "Developer: homeandriy", "version": "Version {version}", "type": "Type", "service": "Service", "all_types": "All types", "all_services": "All services", "modem": "Modem", "tuner": "Tuner", "internet": "Internet", "television": "Television", "receipt": "Receipt", "issue": "Issue", "operation": "Operation", "contract": "Contract number", "recognized_text": "Serial number / MAC / text", "date_time": "Date and time", "model_name": "Model name", "search": "Search text", "confirm": "Confirmation", "error": "Error", "no_image": "Select an image first.", "folder_missing": "The selected folder is unavailable.", "profile_saved": "AI profile saved.", "profile_required": "Select an AI profile.", "restart_language": "Language saved. It will apply after restart.", "status_ready": "Ready", "barcodes_not_found": "No barcodes found.", "about_text": "Local equipment records and OCR.", "delete_image": "Delete selected photo? Equipment records stay.", "delete_device": "Delete selected equipment record?", "delete_model": "Delete selected model?"}

_pl = {"app_name": "Serial Vision", "recognition": "Rozpoznawanie", "equipment": "Sprzęt", "models": "Modele", "statistics": "Statystyki", "settings": "Ustawienia", "help": "Pomoc", "about": "O programie", "images": "Obrazy", "ocr": "Rozpoznawanie OCR", "barcodes": "Kody kreskowe", "ai": "Rozpoznawanie AI", "ocr_language": "Język OCR", "select_image": "Wybierz obraz", "ocr_empty": "Wynik OCR pojawi się tutaj.", "barcode_empty": "Wynik kodów pojawi się tutaj.", "ai_empty": "Dodaj i wybierz profil AI w Ustawieniach.", "refresh": "Odśwież", "rotate": "Obróć w prawo", "delete": "Usuń", "run_ocr": "Uruchom OCR", "run_barcode": "Odczytaj kody", "choose_folder": "Wybierz folder", "open_folder": "Otwórz folder", "save": "Zapisz", "export": "Eksport CSV", "language": "Język interfejsu", "image_folder": "Folder obrazów", "tesseract": "Tesseract executable", "ai_profiles": "Profile AI", "profile_name": "Nazwa", "provider": "Dostawca", "model": "Model", "api_key": "Klucz API", "add_profile": "Dodaj profil", "remove_profile": "Usuń profil", "no_profiles": "Brak profili AI.", "developer": "Programista: homeandriy", "version": "Wersja {version}", "type": "Typ", "service": "Usługa", "all_types": "Wszystkie typy", "all_services": "Wszystkie usługi", "modem": "Modem", "tuner": "Tuner", "internet": "Internet", "television": "Telewizja", "receipt": "Przyjęcie", "issue": "Wydanie", "operation": "Operacja", "contract": "Numer umowy", "recognized_text": "Numer seryjny / MAC / tekst", "date_time": "Data i czas", "model_name": "Nazwa modelu", "search": "Szukaj tekstu", "confirm": "Potwierdzenie", "error": "Błąd", "no_image": "Najpierw wybierz obraz.", "folder_missing": "Wybrany folder jest niedostępny.", "profile_saved": "Profil AI zapisano.", "profile_required": "Wybierz profil AI.", "restart_language": "Język zapisano. Zostanie zastosowany po restarcie.", "status_ready": "Gotowe", "barcodes_not_found": "Nie znaleziono kodów kreskowych.", "about_text": "Lokalna ewidencja sprzętu i OCR.", "delete_image": "Usunąć wybrane zdjęcie? Rekordy sprzętu pozostaną.", "delete_device": "Usunąć wybrany rekord sprzętu?", "delete_model": "Usunąć wybrany model?"}

TEXT = {"uk": _uk, "en": _en, "pl": _pl}
for _locale, _values in TEXT.items():
    _values.setdefault("open", {"en": "Open", "pl": "Otwórz"}.get(_locale, "Відкрити"))
    _values.setdefault("exit", {"en": "Exit", "pl": "Wyjdź"}.get(_locale, "Вийти"))
    _values.setdefault("copy", {"en": "Copy", "pl": "Kopiuj"}.get(_locale, "Копіювати"))
    _values.setdefault("add_to_database", {"en": "Add to database", "pl": "Dodaj do bazy"}.get(_locale, "Додати в БД"))
    _values.setdefault("add_raw_to_database", {"en": "Add unformatted to database", "pl": "Dodaj bez formatowania do bazy"}.get(_locale, "Додати в БД неформатовано"))
    _values.setdefault("new_equipment", {"en": "New equipment record", "pl": "Nowy wpis sprzętu"}.get(_locale, "Новий запис обладнання"))
    _values.setdefault("add_record", {"en": "Add record", "pl": "Dodaj wpis"}.get(_locale, "Додати запис"))
    _values.setdefault("edit", {"en": "Edit", "pl": "Edytuj"}.get(_locale, "Редагувати"))
